config-version: 1  #don't touch this

Setting:
  Whitelist:
    Movement:
      Enabled: false
      Message: "&c길드에 소속되어 있지 않으면 움직임이 제한됩니다"
    Join:
      Enabled: false
      Message: "&c서버에서 플레이하기 위해서는 길드에 소속되어 있어야 됩니다"

PvPDeathPenalty:
  Enabled: false
  Max-TryCount: 5
  Max-LoseCount: 2
  Additional-Percent: 0.05
  Whitelist:
    - pvp_world